name: ktop Release

on:
  push:
    tags:
      - 'v*.*.**'

jobs:
  go-release:
    name: goreleaser-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    - name: Binary release
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASER_SECRET }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.43